
import { User } from '@/types/auth';

// Fix the date values to be proper Date objects
export const mockUsers = [
  {
    id: '1',
    email: 'doctor@omnicare.com',
    name: 'Dr. John Smith',
    role: 'doctor',
    permissions: ['patients:read', 'patients:write', 'prescriptions:write'],
    createdAt: new Date('2022-01-15'),
    lastLogin: new Date('2023-05-10'),
  },
  {
    id: '2',
    email: 'nurse@omnicare.com',
    name: 'Jane Doe',
    role: 'nurse',
    permissions: ['patients:read', 'vitals:write', 'medications:administer'],
    createdAt: new Date('2022-03-20'),
    lastLogin: new Date('2023-05-05'),
  },
  {
    id: '3',
    email: 'pharmacist@omnicare.com',
    name: 'Robert Lee',
    role: 'pharmacist',
    permissions: ['medications:read', 'medications:write', 'prescriptions:process'],
    createdAt: new Date('2022-05-01'),
    lastLogin: new Date('2023-05-01'),
  },
  {
    id: '4',
    email: 'admin@omnicare.com',
    name: 'Susan Green',
    role: 'admin',
    permissions: ['all'],
    createdAt: new Date('2022-06-10'),
    lastLogin: new Date('2023-04-25'),
  },
  {
    id: '5',
    email: 'patient@omnicare.com',
    name: 'Mark Johnson',
    role: 'patient',
    permissions: ['self:read', 'appointments:read'],
    createdAt: new Date('2022-07-01'),
    lastLogin: new Date('2023-05-12'),
  },
  {
    id: '6',
    email: 'labtech.emily@example.com',
    name: 'Emily White',
    role: 'lab_technician',
    permissions: ['patients:read', 'lab_results:read', 'lab_results:write'],
    createdAt: new Date('2022-08-15'),
    lastLogin: new Date('2023-04-20'),
  },
  {
    id: '7',
    email: 'radiologist.david@example.com',
    name: 'David Brown',
    role: 'radiologist',
    permissions: ['patients:read', 'imaging:read', 'imaging:write'],
    createdAt: new Date('2022-09-01'),
    lastLogin: new Date('2023-03-15'),
  },
  {
    id: '8',
    email: 'therapist.linda@example.com',
    name: 'Linda Perez',
    role: 'therapist',
    permissions: ['patients:read', 'treatment_plans:write', 'progress_notes:write'],
    createdAt: new Date('2022-10-10'),
    lastLogin: new Date('2023-02-28'),
  },
  {
    id: '9',
    email: 'receptionist.kevin@example.com',
    name: 'Kevin Rodriguez',
    role: 'receptionist',
    permissions: ['patients:read', 'appointments:read', 'appointments:write'],
    createdAt: new Date('2022-11-01'),
    lastLogin: new Date('2023-01-05'),
  },
  {
    id: '10',
    email: 'medicalassistant.ashley@example.com',
    name: 'Ashley Wilson',
    role: 'medical_assistant',
    permissions: ['patients:read', 'vitals:read', 'vitals:write'],
    createdAt: new Date('2022-12-15'),
    lastLogin: new Date('2023-05-01'),
  },
] as User[];
